### ISSUE TITLE
Ghost submodules messing up the repo

### ISSUE THREAD

**Issue by jluttine** [modelica-3rdparty/msgpack-modelica#35]
If I understand correctly, the repository is somehow messed up with submodules:

```
$ git submodule status
fatal: no submodule mapping found in .gitmodules for path 'MessagePack/Resources/C-Sources/msgpack-c/external/boost/predef'
```

That folder isn't a submodule but there is some hidden reference as if it was. Based on this: https://stackoverflow.com/a/4185579 I ran the following:
```
$ git ls-files --stage | grep 160000
160000 1e8d1c2cfcac343305e2182f665742b9e38f7452 0       MessagePack/Resources/C-Sources/msgpack-c/external/boost/predef
160000 c2beb74b90969f369c62d0dea68aa5f0e203268e 0       MessagePack/Resources/C-Sources/msgpack-c/external/boost/preprocessor
```

The solution is to remove those directories.

I'm not at all familiar with this package, so there might be something else going on..

**Comment by jluttine** [comment]
Another option is, I suppose, that those are supposed to be submodules and there's just `.gitmodules` file missing from the repo.

**Comment by sjoelund** [comment]
It's a submodule in the upstream msgpack-c repository. It doesn't seem to be needed to compile the project, so I will just remove that .gitmodules file (MessagePack/Resources/C-Sources/msgpack-c/.gitmodules).
