### ISSUE TITLE
Windows platform support for string streams

### ISSUE THREAD

**Issue by tbeu** [modelica-3rdparty/msgpack-modelica#7]
Is there any chance to get it running on Windows, i.e. avoid error '''Error
in MessagePack.Utilities.Stream.Stream: String streams are not implemented for this platform'''? See e.g. http://stackoverflow.com/questions/10305095/can-i-replace-a-call-to-open-memstream-with-a-malloc-and-an-implicit-cast for replacing open_memstream by CreateFileMapping/MapViewOfFile.

**Comment by sjoelund** [comment]
This is fixed with #14, correct?

**Comment by tbeu** [comment]
Yes, fixed. Thanks.
